server:
  port: 8080
  servlet:
    context-path: /luanniao

spring:
  application:
    name: luanniao
  banner:
    location: banner.txt
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luanniao?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 12345678
    # Hikari 连接池配置
    # 最小空闲连接数量
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: luanniao
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # liquibase 配置
  liquibase:
    enabled: true
    # check-change-log-location: true # 检测 log 文件是否存在
    change-log: classpath:liquibase/master.xml # log 文件位置
    drop-first: false # 是否删除数据库
  redis:
    redisson:
      client-name: luanniao
      database: 0
      address: redis://127.0.0.1:6379
      password: 12345678
      connect-timeout: 10000
      idle-connection-timeout: 10000
      timeout: 10000
      retry-attempts: 3
      connection-minimum-idle-size: 5
      connection-pool-size: 10
      retry-interval: 1500
      subscriptions-perConnection: 6
  # jackson
  jackson:
    time-zone: GMT+8

id-worker:
  worker-id: 1
  data-center-id: 1

token:
  # token 有效期，单位：分钟
  expire: 1440

